// This file will be auto-generated by `pnpm db:types` using Supabase CLI.
// For now, we define the types manually to match the Phase 3 migration schema.

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          base_currency: string;
          timezone: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          base_currency?: string;
          timezone?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          display_name?: string | null;
          base_currency?: string;
          timezone?: string;
          updated_at?: string;
        };
      };

      accounts: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          currency: string;
          account_type: string | null;
          initial_balance: string;
          is_archived: boolean;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          currency: string;
          account_type?: string | null;
          initial_balance?: string;
          is_archived?: boolean;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          currency?: string;
          account_type?: string | null;
          initial_balance?: string;
          is_archived?: boolean;
          sort_order?: number;
          updated_at?: string;
        };
      };

      categories: {
        Row: {
          id: string;
          user_id: string | null;
          name: string;
          type: string;
          icon: string | null;
          color: string | null;
          parent_id: string | null;
          sort_order: number;
          is_system: boolean;
          is_archived: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          name: string;
          type: string;
          icon?: string | null;
          color?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_system?: boolean;
          is_archived?: boolean;
          created_at?: string;
        };
        Update: {
          name?: string;
          type?: string;
          icon?: string | null;
          color?: string | null;
          parent_id?: string | null;
          sort_order?: number;
          is_archived?: boolean;
        };
      };

      transactions: {
        Row: {
          id: string;
          user_id: string;
          account_id: string;
          transaction_type: string;
          category_id: string | null;
          amount: string;
          currency: string;
          base_currency: string;
          exchange_rate: string;
          base_amount: string;
          transaction_date: string;
          note: string | null;
          transfer_group_id: string | null;
          exchange_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          account_id: string;
          transaction_type: string;
          category_id?: string | null;
          amount: string;
          currency: string;
          base_currency: string;
          exchange_rate: string;
          base_amount: string;
          transaction_date: string;
          note?: string | null;
          transfer_group_id?: string | null;
          exchange_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          account_id?: string;
          transaction_type?: string;
          category_id?: string | null;
          amount?: string;
          currency?: string;
          base_currency?: string;
          exchange_rate?: string;
          base_amount?: string;
          transaction_date?: string;
          note?: string | null;
          transfer_group_id?: string | null;
          exchange_id?: string | null;
          updated_at?: string;
        };
      };

      exchange_rates: {
        Row: {
          id: string;
          user_id: string;
          base_currency: string;
          quote_currency: string;
          rate: string;
          source: string;
          effective_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          base_currency: string;
          quote_currency: string;
          rate: string;
          source?: string;
          effective_at: string;
          created_at?: string;
        };
        Update: {
          rate?: string;
          source?: string;
          effective_at?: string;
        };
      };

      exchanges: {
        Row: {
          id: string;
          user_id: string;
          from_account_id: string;
          to_account_id: string;
          from_currency: string;
          to_currency: string;
          from_amount: string;
          to_amount: string;
          reference_rate: string | null;
          actual_rate: string;
          fee_amount: string | null;
          fee_currency: string | null;
          transaction_date: string;
          note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          from_account_id: string;
          to_account_id: string;
          from_currency: string;
          to_currency: string;
          from_amount: string;
          to_amount: string;
          reference_rate?: string | null;
          actual_rate: string;
          fee_amount?: string | null;
          fee_currency?: string | null;
          transaction_date: string;
          note?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          from_account_id?: string;
          to_account_id?: string;
          from_currency?: string;
          to_currency?: string;
          from_amount?: string;
          to_amount?: string;
          reference_rate?: string | null;
          actual_rate?: string;
          fee_amount?: string | null;
          fee_currency?: string | null;
          transaction_date?: string;
          note?: string | null;
          updated_at?: string;
        };
      };
    };

    Functions: {
      create_transfer: {
        Args: {
          p_from_account_id: string;
          p_to_account_id: string;
          p_amount: string;
          p_currency: string;
          p_transaction_date: string;
          p_note?: string | null;
        };
        Returns: { transfer_group_id: string };
      };
      create_exchange: {
        Args: {
          p_from_account_id: string;
          p_to_account_id: string;
          p_from_currency: string;
          p_to_currency: string;
          p_from_amount: string;
          p_to_amount: string;
          p_reference_rate?: string | null;
          p_actual_rate: string;
          p_fee_amount?: string | null;
          p_fee_currency?: string | null;
          p_base_currency: string;
          p_transaction_date: string;
          p_note?: string | null;
        };
        Returns: { exchange_id: string };
      };
    };
  };
};

export type Profile = Database["public"]["Tables"]["profiles"]["Row"];
export type Account = Database["public"]["Tables"]["accounts"]["Row"];
export type Category = Database["public"]["Tables"]["categories"]["Row"];
export type Transaction = Database["public"]["Tables"]["transactions"]["Row"];
export type ExchangeRate = Database["public"]["Tables"]["exchange_rates"]["Row"];
export type Exchange = Database["public"]["Tables"]["exchanges"]["Row"];
